In [1]:
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from dotenv import load_dotenv
import os

load_dotenv()


api_key = os.getenv("OPENAI_API_KEY")

In [2]:
model_client = OpenAIChatCompletionClient(model='gpt-4o',api_key=api_key)


In [3]:
agent_1 = AssistantAgent(name='my_assistant', model_client=model_client)

In [4]:
result = await agent_1.run(task='Hello, how are you?')
print(result)

messages=[TextMessage(id='b19698fa-d081-4c2f-b482-7b223afd0b5b', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 10, 6, 7, 57, 363768, tzinfo=datetime.timezone.utc), content='Hello, how are you?', type='TextMessage'), TextMessage(id='2b1b6e0c-3216-4a35-aa84-328fa1b95447', source='my_assistant', models_usage=RequestUsage(prompt_tokens=42, completion_tokens=28), metadata={}, created_at=datetime.datetime(2025, 7, 10, 6, 8, 1, 592423, tzinfo=datetime.timezone.utc), content="Hello! I'm an AI, so I don't have feelings, but I'm here and ready to help you. How can I assist you today?", type='TextMessage')] stop_reason=None


messages=[TextMessage(id='b19698fa-d081-4c2f-b482-7b223afd0b5b', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2025, 7, 10, 6, 7, 57, 363768, tzinfo=datetime.timezone.utc), content='Hello, how are you?', type='TextMessage'), TextMessage(id='2b1b6e0c-3216-4a35-aa84-328fa1b95447', source='my_assistant', models_usage=RequestUsage(prompt_tokens=42, completion_tokens=28), metadata={}, created_at=datetime.datetime(2025, 7, 10, 6, 8, 1, 592423, tzinfo=datetime.timezone.utc), content="Hello! I'm an AI, so I don't have feelings, but I'm here and ready to help you. How can I assist you today?", type='TextMessage')] stop_reason=None